--- 
services: 
  beta:
    build:
      context: .
      dockerfile: ./beta/Dockerfile
    networks:
      - app-network
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    restart: always

  embed:
    build:
      context: .
      dockerfile: ./embed/Dockerfile
    networks:
      - embed-network
    command: npm run start:embed
    environment:
      - NODE_ENV=development
    ports:
      - "8081:8080"
    restart: always

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - beta
      - embed
    networks:
      - app-network
      - embed-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email auggod@resonate.is --agree-tos --no-eff-email --force-renewal -d stream.resonate.coop

networks:
  embed-network:
    driver: bridge
  app-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/dhparam/"
      o: bind

version: "3.7"
